// Document ID: SRC-LGX-003
// legixy-graph::subnode — サブノード自動抽出（UC-LGX-003 / DD-LGX-003）
//
// TC[RED] フェーズの scaffold。公開 API surface（型・シグネチャ）は DD-LGX-003 §2/§3 に
// 凍結整合させる。データ型（AutoSubnode / SubnodeKind / GraphParseError）は実体を持ち、
// 抽出・正規化・ID 生成・判定・パース統合のロジックは `todo!()` として TC[RED] を失敗させる。
// SRC[GREEN] で v3（traceability-engine.v3 lx-graph::subnode / parser）底本どおりに実装する。
//
// 親 chain: DD-LGX-003 → TS-LGX-003 → TC-LGX-003 → 本 SRC-LGX-003。crate 境界は ADR-LGX-020。
//
// 重要・既存 legixy-graph を壊さない: 本 module は `crates/legixy-graph/src/lib.rs` に既存の
// TraceGraph / Node / Edge / NodeId / EdgeKind / GraphError を「変更せず」利用する。新規型は
// 本 module 内に閉じて追加し、`pub mod subnode;` で公開するのみ（既存型の再定義・改名・シグネチャ
// 変更は禁止）。
//
// SHARED-NEED: 統合時に共有 crate（legixy-graph 本体 model / legixy-core）へ移設すべき型・関数:
//   - SubnodeKind（DD-LGX-003 §2.2、本来 legixy-graph::model 所有。既存 Node に subnode_kind
//     フィールドを持たせる整合は DD-LGX-001 統合時に行う。本 stub ではローカル定義）。
//   - Node の追加フィールド（anchor / content_range / heading_levels / subnode_kind）は DD-LGX-001
//     統合時に既存 Node へ追加する（HR7 追加は許容）。本 stub では返却 TraceGraph に AutoGenerated
//     サブノード Node を既存 Node 形（id/type_code/path/parent_id）で格納する。

use std::path::Path;

use indexmap::IndexMap;
use serde::Deserialize;
use sha2::{Digest, Sha256};
use unicode_normalization::UnicodeNormalization;

use crate::{Edge, EdgeKind, Node, NodeId, TraceGraph};

// ---------------------------------------------------------------------------
// 型定義（DD-LGX-003 §2）— 実体（テストが構築・期待値比較できるよう pub フィールド）
// ---------------------------------------------------------------------------

/// 自動生成サブノードの中間表現（DD-LGX-003 §2.1）。
/// 抽出段階でのみ使用し、最終的に `Node` へ変換される。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AutoSubnode {
    /// `"{parent_id}#{hex16}"` 形式（SUBNODE-INV-5/6）。
    pub id: String,
    /// 親ドキュメントノードの NodeId。
    pub parent_id: String,
    /// 正規化前の生見出しテキスト（# マーカー・closing # 除去済、前後 trim 済）。
    pub anchor: String,
    /// 正規化済み見出し階層パス（h2: 1 要素、h3: [h2, h3] の 2 要素）。
    pub heading_path: Vec<String>,
    /// 本文のバイト半開区間 `[body_start, end_byte)`。
    pub content_range: (usize, usize),
}

/// サブノード種別（DD-LGX-003 §2.2、v3 model.rs 踏襲）。
///
/// SHARED-NEED: 本来 legixy-graph::model（共有型）所有。既存 `Node` に `subnode_kind`
/// フィールドを統合する際にここから移設する（ADR-LGX-020）。
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SubnodeKind {
    /// ドキュメントノード（graph.toml の通常ノード）。
    Document,
    /// 自動生成サブノード（Markdown 見出し由来）。
    AutoGenerated,
    /// 明示サブノード（graph.toml の `#s:` 形式宣言）。
    Explicit,
}

/// 未解決エッジ端点（DD-LGX-003 §2.2）。
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MissingEndpoint {
    /// from 側の NodeId がグラフに存在しない。
    From,
    /// to 側の NodeId がグラフに存在しない。
    To,
    /// 両方とも存在しない。
    Both,
}

/// グラフパース実行時失敗（DD-LGX-003 §2.3、exit 1 経路）。
/// 自動抽出の部分失敗は `Err` ではなくスキップ（DD-LGX-003 §6）。
#[derive(Debug, thiserror::Error)]
pub enum GraphParseError {
    /// graph.toml / Markdown ファイル読込 I/O 失敗（`?` 演算子で伝播）。
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    /// graph.toml の TOML 構文不正。
    #[error("toml parse error: {0}")]
    TomlParse(#[from] toml::de::Error),
    /// 不正 edge kind / 絶対パス / `..` セグメント（セキュリティ検証失敗）。
    #[error("validation error: {0}")]
    ValidationError(String),
}

// ---------------------------------------------------------------------------
// 公開 API surface（DD-LGX-003 §3、凍結 HR7）— ロジックは SRC[GREEN] で実装
// ---------------------------------------------------------------------------

/// graph.toml を読み込み、自動抽出を含むグラフ構築を行う（DD-LGX-003 §3）。
/// 同一 graph.toml + 同一 Markdown 群 → 同一 `TraceGraph`（CTX-INV-1 / SUBNODE-INV-1〜6）。
pub fn parse_graph(toml_path: &Path, project_root: &Path) -> Result<TraceGraph, GraphParseError> {
    let content = std::fs::read_to_string(toml_path)?;
    parse_graph_from_str(&content, project_root)
}

/// `parse_graph` の文字列版（DD-LGX-003 §3）。ファイル IO を持ち込まない（テスト・ファジング用）。
/// graph.toml の TOML 文字列と project_root から `TraceGraph` を構築する。
pub fn parse_graph_from_str(
    toml_str: &str,
    project_root: &Path,
) -> Result<TraceGraph, GraphParseError> {
    let raw: RawGraphFile = toml::from_str(toml_str)?;

    let mut nodes: IndexMap<NodeId, Node> = IndexMap::new();

    // 1. raw ノードを document / explicit subnode に分類して定義順に挿入。
    for raw_node in &raw.nodes {
        let parent_id = classify_node(raw_node)?;

        // パストラバーサル防御（NFR-LGX-001.SEC.06）。FS には触れず、明白な上方逸脱のみ拒否。
        validate_path_scope(&raw_node.path)?;

        let node = Node {
            id: raw_node.id.clone(),
            type_code: raw_node.type_code.clone(),
            path: raw_node.path.clone(),
            parent_id,
            // 明示サブノードの見出しアンカー（本文区画解決に使う）。ドキュメント/通常ノードは None。
            anchor: raw_node.anchor.clone(),
        };
        // 縮退（後勝ち）= IndexMap::insert の上書きセマンティクス。
        nodes.insert(raw_node.id.clone(), node);
    }

    // 2. .md ドキュメントノードごとに自動サブノードを抽出。
    let document_entries: Vec<(NodeId, String, String, Vec<u8>)> = raw
        .nodes
        .iter()
        .filter(|n| {
            nodes
                .get(&n.id)
                .map(|stored| stored.parent_id.is_none())
                .unwrap_or(false)
        })
        .filter(|n| n.path.ends_with(".md"))
        .map(|n| {
            (
                n.id.clone(),
                n.path.clone(),
                n.type_code.clone(),
                n.heading_levels.clone().unwrap_or_else(|| vec![2, 3]),
            )
        })
        .collect();

    let mut auto_nodes: Vec<Node> = Vec::new();
    for (parent_id, parent_rel_path, parent_type, levels) in document_entries {
        let abs_path = project_root.join(&parent_rel_path);
        if !abs_path.exists() {
            continue;
        }
        let content = match std::fs::read_to_string(&abs_path) {
            Ok(c) => c,
            Err(_) => continue, // NFR-LGX-001.REL.02: 部分失敗トレランス
        };
        for sub in extract_subnodes_with_levels(&parent_id, &content, &levels) {
            // 明示サブノードが同一 ID で既に存在する場合はスキップ（明示優先）。
            if nodes.contains_key(&sub.id) {
                continue;
            }
            auto_nodes.push(Node {
                type_code: format!("{}-section", parent_type),
                path: parent_rel_path.clone(),
                parent_id: Some(parent_id.clone()),
                // 自動生成サブノードの生見出しテキスト（区画照合・表示用）。
                anchor: Some(sub.anchor.clone()),
                id: sub.id,
            });
        }
    }
    for n in auto_nodes {
        nodes.insert(n.id.clone(), n);
    }

    // 3. 全サブノード（parent_id を持つノード）に対し ParentChild エッジを生成。
    let mut parent_child_edges: Vec<Edge> = Vec::new();
    for n in nodes.values() {
        if let Some(pid) = &n.parent_id {
            parent_child_edges.push(Edge {
                from: pid.clone(),
                to: n.id.clone(),
                kind: EdgeKind::ParentChild,
            });
        }
    }

    // 4. raw エッジを型付きエッジへ変換。不正 kind は ValidationError で即時 Err。
    let mut edges: Vec<Edge> = Vec::new();
    for raw_edge in raw.edges {
        let kind = parse_edge_kind(raw_edge.kind.as_deref()).ok_or_else(|| {
            GraphParseError::ValidationError(format!(
                "unknown edge kind: {:?} (edge {} -> {})",
                raw_edge.kind, raw_edge.from, raw_edge.to
            ))
        })?;
        edges.push(Edge {
            from: raw_edge.from,
            to: raw_edge.to,
            kind,
        });
    }

    // 5. ParentChild エッジを末尾に追加（両端点とも nodes 内）。
    edges.extend(parent_child_edges);

    let node_vec: Vec<Node> = nodes.into_values().collect();
    Ok(TraceGraph::from_parts(node_vec, edges))
}

// ---------------------------------------------------------------------------
// graph.toml デシリアライズ（v3 parser.rs 底本、非公開）
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, Default)]
struct RawGraphFile {
    #[serde(default)]
    nodes: Vec<RawNode>,
    #[serde(default)]
    edges: Vec<RawEdge>,
}

#[derive(Debug, Deserialize)]
struct RawNode {
    id: String,
    #[serde(rename = "type")]
    type_code: String,
    path: String,
    #[serde(default)]
    parent: Option<String>,
    /// 明示サブノード（`#s:`）の見出しアンカー（例 `## 状態遷移`）。本文区画の解決に使う（LGX-EXT-001 §4.1）。
    #[serde(default)]
    anchor: Option<String>,
    /// Phase 2 Block D: ドキュメント別の見出しレベル指定（既定 [2, 3]）。
    #[serde(default)]
    heading_levels: Option<Vec<u8>>,
}

#[derive(Debug, Deserialize)]
struct RawEdge {
    from: String,
    to: String,
    #[serde(default)]
    kind: Option<String>,
}

/// raw ノードを分類し、サブノードなら親 NodeId を返す（v3 parser.rs:207-239 底本）。
/// 明示サブノード（`#s:`）は parent フィールド必須。自動生成形式は prefix を親に推論。
fn classify_node(raw: &RawNode) -> Result<Option<NodeId>, GraphParseError> {
    let parent_from_field = raw
        .parent
        .as_ref()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());

    if let Some((prefix, fragment)) = raw.id.split_once('#') {
        if let Some(name) = fragment.strip_prefix("s:") {
            let _ = name;
            let parent = parent_from_field.ok_or_else(|| {
                GraphParseError::ValidationError(format!(
                    "explicit subnode '{}' requires a `parent` field (SUBNODE-INV-1)",
                    raw.id
                ))
            })?;
            return Ok(Some(parent));
        }
        // 自動生成形式・不明 `#` 形式とも親を推論（明示宣言扱い）。
        let parent = parent_from_field.unwrap_or_else(|| prefix.to_string());
        return Ok(Some(parent));
    }

    if let Some(parent) = parent_from_field {
        return Ok(Some(parent));
    }
    Ok(None)
}

/// raw edge kind 文字列を `EdgeKind` へ変換（v3 parser.rs:241-249 底本）。未知は None。
fn parse_edge_kind(raw: Option<&str>) -> Option<EdgeKind> {
    match raw {
        None => Some(EdgeKind::Chain),
        Some("chain") => Some(EdgeKind::Chain),
        Some("custom") => Some(EdgeKind::Custom),
        Some("parent_child") | Some("parent-child") => Some(EdgeKind::ParentChild),
        _ => None,
    }
}

/// `project_root` 外への `..` 逸脱・絶対パスを拒否（NFR-LGX-001.SEC.06、v3 parser.rs:252-270 底本）。
fn validate_path_scope(path: &str) -> Result<(), GraphParseError> {
    let p = Path::new(path);
    if p.is_absolute() {
        return Err(GraphParseError::ValidationError(format!(
            "absolute path not allowed in graph.toml: {}",
            path
        )));
    }
    for comp in p.components() {
        if matches!(comp, std::path::Component::ParentDir) {
            return Err(GraphParseError::ValidationError(format!(
                "path escapes project_root: {}",
                path
            )));
        }
    }
    Ok(())
}

/// h2/h3 固定で自動サブノードを抽出（DD-LGX-003 §3）。
/// `extract_subnodes_with_levels(parent_id, content, &[2, 3])` の糖衣。
pub fn extract_subnodes(parent_id: &str, content: &str) -> Vec<AutoSubnode> {
    extract_subnodes_with_levels(parent_id, content, &[2, 3])
}

/// 指定レベルの ATX 見出しのみ抽出（DD-LGX-003 §3、M-2 heading_levels 内部属性）。
/// `levels` 空の場合は空 `Vec`（クラッシュなし、REQ.10）。同一入力→同一結果。
pub fn extract_subnodes_with_levels(
    parent_id: &str,
    content: &str,
    levels: &[u8],
) -> Vec<AutoSubnode> {
    let bytes = content.as_bytes();
    let mut pending: Vec<PendingHeading> = Vec::new();

    let mut offset = 0;
    let mut current_h2: Option<String> = None;

    let target = |lv: u8| levels.contains(&lv);

    while offset < bytes.len() {
        let line_end = memchr_newline(bytes, offset).unwrap_or(bytes.len());
        let line = std::str::from_utf8(&bytes[offset..line_end]).unwrap_or("");
        let trimmed_start = line.len() - line.trim_start().len();
        let trimmed = line.trim_start();

        if let Some(level) = atx_level(trimmed) {
            if level == 1 {
                current_h2 = None;
            } else if target(level) {
                let raw = trimmed[(level as usize)..]
                    .trim_start_matches(' ')
                    .trim_end()
                    .trim_end_matches('#')
                    .trim_end();
                let normalized = normalize_heading(raw);
                if normalized.is_empty() {
                    if level == 2 {
                        current_h2 = None;
                    }
                } else {
                    let body_start = next_line_start(bytes, line_end);
                    if level == 2 {
                        current_h2 = Some(normalized.clone());
                    }
                    let h2_context = if level == 3 { current_h2.clone() } else { None };
                    pending.push(PendingHeading {
                        level,
                        raw_line: raw.to_string(),
                        normalized,
                        line_start: offset + trimmed_start,
                        body_start,
                        h2_context,
                    });
                }
            }
        }

        offset = next_line_start(bytes, line_end);
    }

    let mut out: Vec<AutoSubnode> = Vec::with_capacity(pending.len());
    for (idx, ph) in pending.iter().enumerate() {
        let end_byte = pending
            .iter()
            .skip(idx + 1)
            .find(|next| next.level <= ph.level)
            .map(|next| next.line_start)
            .unwrap_or(bytes.len());
        let heading_path = match (ph.level, &ph.h2_context) {
            (3, Some(h2)) => vec![h2.clone(), ph.normalized.clone()],
            _ => vec![ph.normalized.clone()],
        };
        let id = generate_subnode_id(parent_id, &heading_path);
        out.push(AutoSubnode {
            id,
            parent_id: parent_id.to_string(),
            anchor: ph.raw_line.clone(),
            heading_path,
            content_range: (ph.body_start, end_byte),
        });
    }
    out
}

/// 見出し抽出の内部作業型（DD-LGX-003 §2.1、非公開）。
struct PendingHeading {
    level: u8,
    raw_line: String,
    normalized: String,
    line_start: usize,
    body_start: usize,
    h2_context: Option<String>,
}

/// 行頭が `#` × n（n=1..=6）＋空白/タブ/行末のとき ATX 見出しレベルを返す（v3 extractor.rs:117-138 底本）。
fn atx_level(line: &str) -> Option<u8> {
    let mut count = 0u8;
    for b in line.bytes() {
        if b == b'#' {
            count = count.saturating_add(1);
            if count > 6 {
                return None;
            }
        } else {
            break;
        }
    }
    if count == 0 {
        return None;
    }
    let rest = &line.as_bytes()[count as usize..];
    match rest.first() {
        None => Some(count),
        Some(&b' ') | Some(&b'\t') => Some(count),
        _ => None,
    }
}

fn memchr_newline(bytes: &[u8], start: usize) -> Option<usize> {
    bytes[start..]
        .iter()
        .position(|&b| b == b'\n')
        .map(|p| start + p)
}

fn next_line_start(bytes: &[u8], line_end: usize) -> usize {
    if line_end >= bytes.len() {
        return bytes.len();
    }
    line_end + 1
}

/// サブノード ID を生成（DD-LGX-003 §3、SUBNODE-INV-5、v3 id_gen.rs:7-20 実測底本）。
/// `{parent_id}#{SHA-256(parent_id + "|" + heading_path.join("|"))[0..16]}` を小文字 hex で生成。
pub fn generate_subnode_id(parent_id: &str, heading_path: &[String]) -> String {
    let joined = heading_path.join("|");
    let mut hash_input = String::with_capacity(parent_id.len() + 1 + joined.len());
    hash_input.push_str(parent_id);
    hash_input.push('|');
    hash_input.push_str(&joined);

    let mut hasher = Sha256::new();
    hasher.update(hash_input.as_bytes());
    let digest = hasher.finalize();
    let hex_str = hex::encode(digest);

    format!("{}#{}", parent_id, &hex_str[..16])
}

/// 見出し正規化（DD-LGX-003 §3 / §5.1、5 段階、v3 normalizer.rs 実測底本）。
/// ①装飾除去 ②NFC ③U+3000→ASCII空白 ④trim ⑤連続空白統合。
pub fn normalize_heading(text: &str) -> String {
    // 1. Markdown 装飾除去（長いマーカー優先: ** / __ / ~~ → * / _ / `）。
    //    単一 '_' / '*' の除去が新たな "~~" 等の二連マーカーを生成しうるため（例: "~_~" → "~~"）、
    //    不動点まで反復して冪等性を保つ（TS-LGX-003 ケース 13 の normalize 冪等性 property）。
    let mut s = text.to_string();
    loop {
        let before = s.clone();
        for marker in &["**", "__", "~~"] {
            s = s.replace(marker, "");
        }
        s = s.replace('*', "");
        s = s.replace('_', "");
        s = s.replace('`', "");
        if s == before {
            break;
        }
    }

    // 2. NFC 正規化
    let s: String = s.nfc().collect();

    // 3. 全角スペース U+3000 → ASCII スペース
    let s = s.replace('\u{3000}', " ");

    // 4. 前後トリム
    let s = s.trim();

    // 5. 連続 whitespace を単一 ASCII スペースへ統合
    let mut out = String::with_capacity(s.len());
    let mut prev_ws = false;
    for c in s.chars() {
        if c.is_whitespace() {
            if !prev_ws {
                out.push(' ');
            }
            prev_ws = true;
        } else {
            out.push(c);
            prev_ws = false;
        }
    }
    out
}

/// fragment が自動生成形式（ちょうど 16 文字小文字 hex `0-9a-f`）か判定
/// （DD-LGX-003 §3、SUBNODE-INV-6、v3 id_gen.rs:64-71 実測底本）。
pub fn is_auto_generated_fragment(fragment: &str) -> bool {
    if fragment.len() != 16 {
        return false;
    }
    fragment
        .chars()
        .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c))
}

/// 明示サブノード名（`#s:` 以降）の文字制約検証
/// （DD-LGX-003 §3、LGX-EXT-001 §4.5.2、v3 id_gen.rs:27-59 実測底本）。
/// 英数・ハイフン・アンダースコア、両端英数、1〜63 文字。
pub fn validate_explicit_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("explicit subnode name must not be empty".to_string());
    }
    if name.len() > 63 {
        return Err(format!(
            "explicit subnode name length {} exceeds 63",
            name.len()
        ));
    }
    for c in name.chars() {
        if !(c.is_ascii_alphanumeric() || c == '-' || c == '_') {
            return Err(format!(
                "explicit subnode name contains invalid character '{}'",
                c
            ));
        }
    }
    let first = match name.chars().next() {
        Some(c) => c,
        None => return Err("explicit subnode name must not be empty".to_string()),
    };
    let last = match name.chars().next_back() {
        Some(c) => c,
        None => return Err("explicit subnode name must not be empty".to_string()),
    };
    if !first.is_ascii_alphanumeric() {
        return Err(format!(
            "explicit subnode name must start with an alphanumeric character (got '{}')",
            first
        ));
    }
    if !last.is_ascii_alphanumeric() {
        return Err(format!(
            "explicit subnode name must end with an alphanumeric character (got '{}')",
            last
        ));
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// 統合補助（テストが SubnodeKind を Node から引けないため、本 stub が提供する分類面）
//
// SHARED-NEED: 統合時は既存 Node に subnode_kind フィールドを持たせ本関数を撤去する。
// 本 stub では「AutoGenerated サブノードへの ParentChild エッジが親から張られる」ことと
// 「自動生成 fragment 形式」を既存 Node/Edge から検証する経路を提供する。
// ---------------------------------------------------------------------------

/// 指定ノード ID の `#` fragment から `SubnodeKind` を分類する（DD-LGX-003 §2.2）。
/// `#s:` → Explicit、16 文字小文字 hex → AutoGenerated、`#` なし → Document。
/// SHARED-NEED: 統合時は Node.subnode_kind を直接参照する形へ置換する。
pub fn classify_subnode_kind(node_id: &str) -> SubnodeKind {
    match node_id.split_once('#') {
        None => SubnodeKind::Document,
        Some((_, fragment)) => {
            if fragment.starts_with("s:") {
                SubnodeKind::Explicit
            } else if is_auto_generated_fragment(fragment) {
                SubnodeKind::AutoGenerated
            } else {
                SubnodeKind::Explicit
            }
        }
    }
}

/// グラフ中の ParentChild エッジ（親→サブノード）を収集する補助
/// （TS-LGX-003 ケース 17 の ParentChild 生成検証用）。
/// SHARED-NEED: 統合時は TraceGraph 側 API（edges() の filter）に集約してよい。
pub fn parent_child_edges(graph: &TraceGraph) -> Vec<Edge> {
    graph
        .edges()
        .iter()
        .filter(|e| matches!(e.kind, crate::EdgeKind::ParentChild))
        .cloned()
        .collect()
}
